import '../globals.css';

// components
import ModelSelect from '@/features/ModelSelect';
import ModelGrid from '@/features/ModelGrid';
import SettingsSideBar from '@/features/SettingsSideBar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex w-screen h-screen text-gray-700">
          {/* Model Selection Sidebar */}
          <ModelSelect />

          {/* Chat History & Settings */}
          <SettingsSideBar />

          {/* Page Main */}
          {children}
        </main>
      </body>
    </html>
  );
}
